name: Release BufferCopy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version(ex. 1.0.0)"
        required: true
        default: "0.0.0"
      release:
        description: "release"
        required: true
        default: "false"

env:
  VERSION: ${{ github.event.inputs.version }}
  RELEASE: ${{ github.event.inputs.release }}
  RUNTIME: "win-x64"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish ./src/BufferCopy/ -c release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:Version=${{ env.VERSION }} -r ${{ env.RUNTIME }} -o /tmp/publish/${{ env.RUNTIME }}/
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: ${{ env.RUNTIME }}
          path: /tmp/publish/${{ env.RUNTIME }}/ 
           

  release:
    if: github.event.inputs.release == 'true'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create GitTag
        run: git tag Release/${{ env.VERSION }}
        
      - name: Push GitTag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
          
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release/${{ env.VERSION }}
          release_name: BufferCopy Ver.${{ env.VERSION }}
          draft: true
          prerelease: false
          
      - name: Download Release Asset
        uses: actions/download-artifact@v3
        id: download_asset
        with:
          name: ${{ env.RUNTIME }}
          path: /tmp/release/${{ env.RUNTIME }}/ 
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_asset.outputs.download-path }}/BufferCopy.exe
          asset_name: BufferCopy.exe
          asset_content_type: application/octet-stream
      
