name: Release BufferCopy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version(ex. 1.0.0)"
        required: true
      release:
        description: "release"
        required: true
        default: "false"

env:
  VERSION: ${{ github.event.inputs.version }}
  RELEASE: ${{ github.event.inputs.release }}
  RUNTIME: "win-x64"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish ./src/BufferCopy/ -c release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:Version=${{ env.VERSION }} -r ${{ env.RUNTIME }} -o /tmp/publish/${{ env.RUNTIME }}/
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: ${{ env.RUNTIME }}
          path: /tmp/publish/${{ env.RUNTIME }}/ 
